# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('at_bats', models.IntegerField()),
                ('hits', models.IntegerField()),
                ('runs_batted', models.IntegerField()),
                ('homeruns', models.IntegerField()),
                ('runs', models.IntegerField()),
                ('batting_average', models.FloatField()),
            ],
        ),
    ]
